### ISSUE TITLE
Text and arguments fields in the Settings UI are unreadable

### ISSUE THREAD

**Issue by ross-g** [yurihs/sublime-vscode-theme#2]
The theme is causing black text on dark grey background in the settings menu, meaning you can only read the text by highlighting it.
Sublime VSCode theme
![image](https://user-images.githubusercontent.com/9258768/70321457-480bb100-181f-11ea-8a81-ae8c3f665117.png)

Builtin Monokai theme
![image](https://user-images.githubusercontent.com/9258768/70321581-8f923d00-181f-11ea-8ab6-1050dcaae6a6.png)

There is a similar issue with highlighting in the argument array style settings fields, where you can add multiple arguments with the 'Add Item' button.

**Comment by yurihs** [comment]
@ross-g Thanks for reporting!

I've managed to fix the contrast in the text and number fields (just published in v1.2.2). The "argument array" fields, however, are still broken when hovered. I'm looking into it, but it doesn't seem fixable at the moment.

If you encounter other problems relating to contrast, please report it in #1.
