### ISSUE TITLE
Wrong missing color style

### ISSUE THREAD

**Issue by Zoltar19XX** [yurihs/sublime-vscode-theme#3]
Hello,

I start using your theme on VSCode. 
I notice that not all types of code is 1:1 from Sublime
![image](https://user-images.githubusercontent.com/72945119/96504186-a6cdf380-1254-11eb-8922-00b2dea42ae2.png)

Is there a change for update?

**Comment by yurihs** [comment]
@Zoltar19XX 

Hello. Thanks for submitting an issue, I hadn't noticed this problem!

I published a new version (v1.4.0) that should add the blue coloring to the function calls.

Please try it out.

**Comment by Zoltar19XX** [comment]
@yurihs Work like a charm!! Ty for a fast fix :)
